"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserSchema = exports.TemplateThumbnailSchema = exports.TemplateAttributeTypeSchema = exports.TemplateAttributesSchema = exports.TemplateAttributeSchema = exports.TemplateSchema = exports.TaskSchema = exports.JobModeSchema = exports.JobStatusSchema = exports.JobSchema = exports.DailyStatsSchema = exports.DetailedStatsSchema = exports.CampaignStatsSchema = exports.ScheduleWhenSchema = exports.ScheduleSchema = exports.OrganizationSchema = exports.CampaignSchema = exports.PassSchema = exports.AuthedSchema = exports.DEFAULT_BASE_URL = exports.parseAuthed = exports.TOKEN_SKEW_SECONDS = exports.BaseAuthProvider = exports.StoredProvider = exports.OAuthProvider = exports.KeysProvider = exports.WidgetsEndpoint = exports.BarcodesEndpoint = exports.ImagesEndpoint = exports.ScannersEndpoint = exports.WorkflowJobsEndpoint = exports.WorkflowsEndpoint = exports.OrganizationExportersEndpoint = exports.OrganizationDataStoresEndpoint = exports.OrganizationWebhooksEndpoint = exports.OrganizationsEndpoint = exports.TemplatesEndpoint = exports.CampaignWorkflowsEndpoint = exports.CampaignWalletsEndpoint = exports.CampaignEnrollmentsEndpoint = exports.CampaignStatsEndpoint = exports.CampaignJobsEndpoint = exports.CampaignClaimsEndpoint = exports.CampaignPassesEndpoint = exports.CampaignsEndpoint = exports.ClaimsEndpoint = exports.Endpoint = exports.ApiError = exports.HttpRequester = exports.Client = void 0;
exports.CampaignWalletEnrollmentResponseSchema = exports.CampaignWalletsResponseSchema = exports.BarcodeTypeSchema = exports.BarcodeRenderInputSchema = exports.ScannerLogSchema = exports.ExporterLogStatusSchema = exports.ExporterLogSchema = exports.ExporterWhenSchema = exports.ExporterSourceSchema = exports.ExporterInputSchema = exports.ExporterSchema = exports.DataStoreSourceSchema = exports.DataStoreKeyValueSchema = exports.DataStoreInputSchema = exports.DataStoreSchema = exports.WebhookLogSchema = exports.WebhookEventSchema = exports.WebhookInputSchema = exports.WebhookSchema = exports.WalletUpdateReasonSchema = exports.WalletUpdateSchema = exports.CampaignWorkflowRunsWhenSchema = exports.CampaignWorkflowInputSchema = exports.CampaignWorkflowSchema = exports.SnippetLibrarySchema = exports.ImageSchema = exports.WorkflowMessageSchema = exports.WorkflowJobStatusSchema = exports.WorkflowJobSchema = exports.WorkflowSchema = exports.GoogleTemplateSchema = exports.ScannerDeviceInfoSchema = exports.AttributeTypeSchema = exports.AttributeItemSchema = exports.AttributesSchema = exports.ScannerAppSchema = exports.ApiKeySchema = exports.ScannerInviteSchema = exports.MetaValueSchema = exports.MetaValuesSchema = exports.EnrollmentResponseSchema = exports.EnrollmentSchema = exports.ClaimSchema = exports.DomainSchema = void 0;
var Client_1 = require("./Client");
Object.defineProperty(exports, "Client", { enumerable: true, get: function () { return __importDefault(Client_1).default; } });
var HttpRequester_1 = require("./http/HttpRequester");
Object.defineProperty(exports, "HttpRequester", { enumerable: true, get: function () { return __importDefault(HttpRequester_1).default; } });
var ApiError_1 = require("./http/ApiError");
Object.defineProperty(exports, "ApiError", { enumerable: true, get: function () { return ApiError_1.ApiError; } });
var Endpoint_1 = require("./endpoint/Endpoint");
Object.defineProperty(exports, "Endpoint", { enumerable: true, get: function () { return __importDefault(Endpoint_1).default; } });
var ClaimsEndpoint_1 = require("./endpoint/ClaimsEndpoint");
Object.defineProperty(exports, "ClaimsEndpoint", { enumerable: true, get: function () { return __importDefault(ClaimsEndpoint_1).default; } });
var CampaignsEndpoint_1 = require("./endpoint/CampaignsEndpoint");
Object.defineProperty(exports, "CampaignsEndpoint", { enumerable: true, get: function () { return __importDefault(CampaignsEndpoint_1).default; } });
var PassesEndpoint_1 = require("./endpoint/campaigns/PassesEndpoint");
Object.defineProperty(exports, "CampaignPassesEndpoint", { enumerable: true, get: function () { return __importDefault(PassesEndpoint_1).default; } });
var ClaimsEndpoint_2 = require("./endpoint/campaigns/ClaimsEndpoint");
Object.defineProperty(exports, "CampaignClaimsEndpoint", { enumerable: true, get: function () { return __importDefault(ClaimsEndpoint_2).default; } });
var JobsEndpoint_1 = require("./endpoint/campaigns/JobsEndpoint");
Object.defineProperty(exports, "CampaignJobsEndpoint", { enumerable: true, get: function () { return __importDefault(JobsEndpoint_1).default; } });
var StatsEndpoint_1 = require("./endpoint/campaigns/StatsEndpoint");
Object.defineProperty(exports, "CampaignStatsEndpoint", { enumerable: true, get: function () { return __importDefault(StatsEndpoint_1).default; } });
var EnrollmentsEndpoint_1 = require("./endpoint/campaigns/EnrollmentsEndpoint");
Object.defineProperty(exports, "CampaignEnrollmentsEndpoint", { enumerable: true, get: function () { return __importDefault(EnrollmentsEndpoint_1).default; } });
var WalletsEndpoint_1 = require("./endpoint/campaigns/WalletsEndpoint");
Object.defineProperty(exports, "CampaignWalletsEndpoint", { enumerable: true, get: function () { return __importDefault(WalletsEndpoint_1).default; } });
var WorkflowsEndpoint_1 = require("./endpoint/campaigns/WorkflowsEndpoint");
Object.defineProperty(exports, "CampaignWorkflowsEndpoint", { enumerable: true, get: function () { return __importDefault(WorkflowsEndpoint_1).default; } });
var TemplatesEndpoint_1 = require("./endpoint/TemplatesEndpoint");
Object.defineProperty(exports, "TemplatesEndpoint", { enumerable: true, get: function () { return __importDefault(TemplatesEndpoint_1).default; } });
var OrganizationsEndpoint_1 = require("./endpoint/OrganizationsEndpoint");
Object.defineProperty(exports, "OrganizationsEndpoint", { enumerable: true, get: function () { return __importDefault(OrganizationsEndpoint_1).default; } });
var WebhooksEndpoint_1 = require("./endpoint/organizations/WebhooksEndpoint");
Object.defineProperty(exports, "OrganizationWebhooksEndpoint", { enumerable: true, get: function () { return __importDefault(WebhooksEndpoint_1).default; } });
var DataStoresEndpoint_1 = require("./endpoint/organizations/DataStoresEndpoint");
Object.defineProperty(exports, "OrganizationDataStoresEndpoint", { enumerable: true, get: function () { return __importDefault(DataStoresEndpoint_1).default; } });
var ExportersEndpoint_1 = require("./endpoint/organizations/ExportersEndpoint");
Object.defineProperty(exports, "OrganizationExportersEndpoint", { enumerable: true, get: function () { return __importDefault(ExportersEndpoint_1).default; } });
var WorkflowsEndpoint_2 = require("./endpoint/WorkflowsEndpoint");
Object.defineProperty(exports, "WorkflowsEndpoint", { enumerable: true, get: function () { return __importDefault(WorkflowsEndpoint_2).default; } });
var JobsEndpoint_2 = require("./endpoint/workflows/JobsEndpoint");
Object.defineProperty(exports, "WorkflowJobsEndpoint", { enumerable: true, get: function () { return __importDefault(JobsEndpoint_2).default; } });
var ScannersEndpoint_1 = require("./endpoint/ScannersEndpoint");
Object.defineProperty(exports, "ScannersEndpoint", { enumerable: true, get: function () { return __importDefault(ScannersEndpoint_1).default; } });
var Images_1 = require("./endpoint/Images");
Object.defineProperty(exports, "ImagesEndpoint", { enumerable: true, get: function () { return __importDefault(Images_1).default; } });
var BarcodesEndpoint_1 = require("./endpoint/BarcodesEndpoint");
Object.defineProperty(exports, "BarcodesEndpoint", { enumerable: true, get: function () { return __importDefault(BarcodesEndpoint_1).default; } });
var WidgetsEndpoint_1 = require("./endpoint/WidgetsEndpoint");
Object.defineProperty(exports, "WidgetsEndpoint", { enumerable: true, get: function () { return __importDefault(WidgetsEndpoint_1).default; } });
var KeysProvider_1 = require("./provider/KeysProvider");
Object.defineProperty(exports, "KeysProvider", { enumerable: true, get: function () { return __importDefault(KeysProvider_1).default; } });
var OAuthProvider_1 = require("./provider/OAuthProvider");
Object.defineProperty(exports, "OAuthProvider", { enumerable: true, get: function () { return __importDefault(OAuthProvider_1).default; } });
var StoredProvider_1 = require("./provider/StoredProvider");
Object.defineProperty(exports, "StoredProvider", { enumerable: true, get: function () { return __importDefault(StoredProvider_1).default; } });
var BaseAuthProvider_1 = require("./provider/BaseAuthProvider");
Object.defineProperty(exports, "BaseAuthProvider", { enumerable: true, get: function () { return __importDefault(BaseAuthProvider_1).default; } });
Object.defineProperty(exports, "TOKEN_SKEW_SECONDS", { enumerable: true, get: function () { return BaseAuthProvider_1.TOKEN_SKEW_SECONDS; } });
Object.defineProperty(exports, "parseAuthed", { enumerable: true, get: function () { return BaseAuthProvider_1.parseAuthed; } });
var constants_1 = require("./constants");
Object.defineProperty(exports, "DEFAULT_BASE_URL", { enumerable: true, get: function () { return constants_1.DEFAULT_BASE_URL; } });
// Type system: Zod schemas and inferred TS types live side-by-side. Consumers that just
// want types can `import type { Foo }`; consumers that want runtime validation can
// `import { FooSchema }` and call `.parse(...)` themselves.
var Authed_1 = require("./types/Authed");
Object.defineProperty(exports, "AuthedSchema", { enumerable: true, get: function () { return Authed_1.AuthedSchema; } });
var Pass_1 = require("./types/Pass");
Object.defineProperty(exports, "PassSchema", { enumerable: true, get: function () { return Pass_1.PassSchema; } });
var Campaign_1 = require("./types/Campaign");
Object.defineProperty(exports, "CampaignSchema", { enumerable: true, get: function () { return Campaign_1.CampaignSchema; } });
var Organization_1 = require("./types/Organization");
Object.defineProperty(exports, "OrganizationSchema", { enumerable: true, get: function () { return Organization_1.OrganizationSchema; } });
var Schedule_1 = require("./types/Schedule");
Object.defineProperty(exports, "ScheduleSchema", { enumerable: true, get: function () { return Schedule_1.ScheduleSchema; } });
Object.defineProperty(exports, "ScheduleWhenSchema", { enumerable: true, get: function () { return Schedule_1.ScheduleWhenSchema; } });
var CampaignStats_1 = require("./types/CampaignStats");
Object.defineProperty(exports, "CampaignStatsSchema", { enumerable: true, get: function () { return CampaignStats_1.CampaignStatsSchema; } });
Object.defineProperty(exports, "DetailedStatsSchema", { enumerable: true, get: function () { return CampaignStats_1.DetailedStatsSchema; } });
Object.defineProperty(exports, "DailyStatsSchema", { enumerable: true, get: function () { return CampaignStats_1.DailyStatsSchema; } });
var Job_1 = require("./types/Job");
Object.defineProperty(exports, "JobSchema", { enumerable: true, get: function () { return Job_1.JobSchema; } });
Object.defineProperty(exports, "JobStatusSchema", { enumerable: true, get: function () { return Job_1.JobStatusSchema; } });
Object.defineProperty(exports, "JobModeSchema", { enumerable: true, get: function () { return Job_1.JobModeSchema; } });
Object.defineProperty(exports, "TaskSchema", { enumerable: true, get: function () { return Job_1.TaskSchema; } });
var Template_1 = require("./types/Template");
Object.defineProperty(exports, "TemplateSchema", { enumerable: true, get: function () { return Template_1.TemplateSchema; } });
Object.defineProperty(exports, "TemplateAttributeSchema", { enumerable: true, get: function () { return Template_1.TemplateAttributeSchema; } });
Object.defineProperty(exports, "TemplateAttributesSchema", { enumerable: true, get: function () { return Template_1.TemplateAttributesSchema; } });
Object.defineProperty(exports, "TemplateAttributeTypeSchema", { enumerable: true, get: function () { return Template_1.TemplateAttributeTypeSchema; } });
var TemplateThumbnail_1 = require("./types/TemplateThumbnail");
Object.defineProperty(exports, "TemplateThumbnailSchema", { enumerable: true, get: function () { return TemplateThumbnail_1.TemplateThumbnailSchema; } });
var User_1 = require("./types/User");
Object.defineProperty(exports, "UserSchema", { enumerable: true, get: function () { return User_1.UserSchema; } });
var Domain_1 = require("./types/Domain");
Object.defineProperty(exports, "DomainSchema", { enumerable: true, get: function () { return Domain_1.DomainSchema; } });
var Claim_1 = require("./types/Claim");
Object.defineProperty(exports, "ClaimSchema", { enumerable: true, get: function () { return Claim_1.ClaimSchema; } });
var Enrollment_1 = require("./types/Enrollment");
Object.defineProperty(exports, "EnrollmentSchema", { enumerable: true, get: function () { return Enrollment_1.EnrollmentSchema; } });
Object.defineProperty(exports, "EnrollmentResponseSchema", { enumerable: true, get: function () { return Enrollment_1.EnrollmentResponseSchema; } });
var MetaValues_1 = require("./types/MetaValues");
Object.defineProperty(exports, "MetaValuesSchema", { enumerable: true, get: function () { return MetaValues_1.MetaValuesSchema; } });
Object.defineProperty(exports, "MetaValueSchema", { enumerable: true, get: function () { return MetaValues_1.MetaValueSchema; } });
var ScannerInvite_1 = require("./types/ScannerInvite");
Object.defineProperty(exports, "ScannerInviteSchema", { enumerable: true, get: function () { return ScannerInvite_1.ScannerInviteSchema; } });
var ApiKey_1 = require("./types/ApiKey");
Object.defineProperty(exports, "ApiKeySchema", { enumerable: true, get: function () { return ApiKey_1.ApiKeySchema; } });
var ScannerApp_1 = require("./types/ScannerApp");
Object.defineProperty(exports, "ScannerAppSchema", { enumerable: true, get: function () { return ScannerApp_1.ScannerAppSchema; } });
var Attributes_1 = require("./types/Attributes");
Object.defineProperty(exports, "AttributesSchema", { enumerable: true, get: function () { return Attributes_1.AttributesSchema; } });
Object.defineProperty(exports, "AttributeItemSchema", { enumerable: true, get: function () { return Attributes_1.AttributeItemSchema; } });
Object.defineProperty(exports, "AttributeTypeSchema", { enumerable: true, get: function () { return Attributes_1.AttributeTypeSchema; } });
var ScannerDeviceInfo_1 = require("./types/ScannerDeviceInfo");
Object.defineProperty(exports, "ScannerDeviceInfoSchema", { enumerable: true, get: function () { return ScannerDeviceInfo_1.ScannerDeviceInfoSchema; } });
var GoogleTemplate_1 = require("./types/GoogleTemplate");
Object.defineProperty(exports, "GoogleTemplateSchema", { enumerable: true, get: function () { return GoogleTemplate_1.GoogleTemplateSchema; } });
var Workflow_1 = require("./types/Workflow");
Object.defineProperty(exports, "WorkflowSchema", { enumerable: true, get: function () { return Workflow_1.WorkflowSchema; } });
var WorkflowJob_1 = require("./types/WorkflowJob");
Object.defineProperty(exports, "WorkflowJobSchema", { enumerable: true, get: function () { return WorkflowJob_1.WorkflowJobSchema; } });
Object.defineProperty(exports, "WorkflowJobStatusSchema", { enumerable: true, get: function () { return WorkflowJob_1.WorkflowJobStatusSchema; } });
var WorkflowMessage_1 = require("./types/WorkflowMessage");
Object.defineProperty(exports, "WorkflowMessageSchema", { enumerable: true, get: function () { return WorkflowMessage_1.WorkflowMessageSchema; } });
var Image_1 = require("./types/Image");
Object.defineProperty(exports, "ImageSchema", { enumerable: true, get: function () { return Image_1.ImageSchema; } });
var SnippetLibrary_1 = require("./types/SnippetLibrary");
Object.defineProperty(exports, "SnippetLibrarySchema", { enumerable: true, get: function () { return SnippetLibrary_1.SnippetLibrarySchema; } });
var CampaignWorkflow_1 = require("./types/CampaignWorkflow");
Object.defineProperty(exports, "CampaignWorkflowSchema", { enumerable: true, get: function () { return CampaignWorkflow_1.CampaignWorkflowSchema; } });
Object.defineProperty(exports, "CampaignWorkflowInputSchema", { enumerable: true, get: function () { return CampaignWorkflow_1.CampaignWorkflowInputSchema; } });
Object.defineProperty(exports, "CampaignWorkflowRunsWhenSchema", { enumerable: true, get: function () { return CampaignWorkflow_1.CampaignWorkflowRunsWhenSchema; } });
var WalletUpdate_1 = require("./types/WalletUpdate");
Object.defineProperty(exports, "WalletUpdateSchema", { enumerable: true, get: function () { return WalletUpdate_1.WalletUpdateSchema; } });
Object.defineProperty(exports, "WalletUpdateReasonSchema", { enumerable: true, get: function () { return WalletUpdate_1.WalletUpdateReasonSchema; } });
var Webhook_1 = require("./types/Webhook");
Object.defineProperty(exports, "WebhookSchema", { enumerable: true, get: function () { return Webhook_1.WebhookSchema; } });
Object.defineProperty(exports, "WebhookInputSchema", { enumerable: true, get: function () { return Webhook_1.WebhookInputSchema; } });
Object.defineProperty(exports, "WebhookEventSchema", { enumerable: true, get: function () { return Webhook_1.WebhookEventSchema; } });
var WebhookLog_1 = require("./types/WebhookLog");
Object.defineProperty(exports, "WebhookLogSchema", { enumerable: true, get: function () { return WebhookLog_1.WebhookLogSchema; } });
var DataStore_1 = require("./types/DataStore");
Object.defineProperty(exports, "DataStoreSchema", { enumerable: true, get: function () { return DataStore_1.DataStoreSchema; } });
Object.defineProperty(exports, "DataStoreInputSchema", { enumerable: true, get: function () { return DataStore_1.DataStoreInputSchema; } });
Object.defineProperty(exports, "DataStoreKeyValueSchema", { enumerable: true, get: function () { return DataStore_1.DataStoreKeyValueSchema; } });
Object.defineProperty(exports, "DataStoreSourceSchema", { enumerable: true, get: function () { return DataStore_1.DataStoreSourceSchema; } });
var Exporter_1 = require("./types/Exporter");
Object.defineProperty(exports, "ExporterSchema", { enumerable: true, get: function () { return Exporter_1.ExporterSchema; } });
Object.defineProperty(exports, "ExporterInputSchema", { enumerable: true, get: function () { return Exporter_1.ExporterInputSchema; } });
Object.defineProperty(exports, "ExporterSourceSchema", { enumerable: true, get: function () { return Exporter_1.ExporterSourceSchema; } });
Object.defineProperty(exports, "ExporterWhenSchema", { enumerable: true, get: function () { return Exporter_1.ExporterWhenSchema; } });
var ExporterLog_1 = require("./types/ExporterLog");
Object.defineProperty(exports, "ExporterLogSchema", { enumerable: true, get: function () { return ExporterLog_1.ExporterLogSchema; } });
Object.defineProperty(exports, "ExporterLogStatusSchema", { enumerable: true, get: function () { return ExporterLog_1.ExporterLogStatusSchema; } });
var ScannerLog_1 = require("./types/ScannerLog");
Object.defineProperty(exports, "ScannerLogSchema", { enumerable: true, get: function () { return ScannerLog_1.ScannerLogSchema; } });
var Barcode_1 = require("./types/Barcode");
Object.defineProperty(exports, "BarcodeRenderInputSchema", { enumerable: true, get: function () { return Barcode_1.BarcodeRenderInputSchema; } });
Object.defineProperty(exports, "BarcodeTypeSchema", { enumerable: true, get: function () { return Barcode_1.BarcodeTypeSchema; } });
var WalletsEndpoint_2 = require("./endpoint/campaigns/WalletsEndpoint");
Object.defineProperty(exports, "CampaignWalletsResponseSchema", { enumerable: true, get: function () { return WalletsEndpoint_2.CampaignWalletsResponseSchema; } });
Object.defineProperty(exports, "CampaignWalletEnrollmentResponseSchema", { enumerable: true, get: function () { return WalletsEndpoint_2.CampaignWalletEnrollmentResponseSchema; } });
