// Generated by scripts/build-docs-nav.mjs. Do not edit manually.

import type { DefaultTheme } from 'vitepress'

export const sidebar: DefaultTheme.SidebarItem[] = 
[
  {
    "text": "Introduction",
    "link": "/"
  },
  {
    "text": "Installing",
    "link": "/installing"
  },
  {
    "text": "Setup",
    "link": "/setup"
  },
  {
    "text": "Usage",
    "link": "/usage/",
    "collapsed": false,
    "items": [
      {
        "text": "Campaigns",
        "link": "/usage/campaigns"
      },
      {
        "text": "Passes",
        "link": "/usage/passes"
      },
      {
        "text": "Enrollments",
        "link": "/usage/enrollments"
      },
      {
        "text": "Wallets",
        "link": "/usage/wallets"
      },
      {
        "text": "Campaign Workflows",
        "link": "/usage/campaign-workflows"
      },
      {
        "text": "Templates",
        "link": "/usage/templates"
      },
      {
        "text": "Organizations",
        "link": "/usage/organizations"
      },
      {
        "text": "Images",
        "link": "/usage/images"
      },
      {
        "text": "Scanners",
        "link": "/usage/scanners"
      },
      {
        "text": "Workflows",
        "link": "/usage/workflows"
      },
      {
        "text": "Barcodes",
        "link": "/usage/barcodes"
      },
      {
        "text": "Widgets",
        "link": "/usage/widgets"
      }
    ]
  }
]
