/**
 * Ordered VitePress sidebar manifest for canonical docs pages.
 *
 * Generated by scripts/split-readme.mjs. Edit to reorder nav or add pages.
 * Run `pnpm docs:build:nav` to regenerate the sidebar.
 */

/** @typedef {{ name: string; source: string; title: string; targetDir?: string }} SyncedDocPage */

/** @type {SyncedDocPage[]} Optional synced pages copied from elsewhere in the repo. */
export const syncedPages = [];

/**
 * Top-level docs navigation entries in sidebar order.
 *
 * @type {Array<
 *   | { kind: 'overview'; title: string }
 *   | { kind: 'page'; slug: string; title: string; maxDepth?: number; pinnedBottom?: true }
 *   | { kind: 'group'; slug: string; title: string; pages: SyncedDocPage[] }
 * >}
 */
export const docsNav = [
  { kind: 'overview', title: 'Introduction' },
  { kind: 'page', slug: "installing", title: "Installing" },
  { kind: 'page', slug: "developing", title: "Developing" },
  { kind: 'page', slug: "building", title: "Building" },
  { kind: 'page', slug: "publishing", title: "Publishing" },
  { kind: 'page', slug: "runtime-validation", title: "Runtime validation" },
  { kind: 'page', slug: "examples", title: "Examples", maxDepth: 3 },
];

/** Slugs of canonical overview pages committed under docs/<slug>/index.md. */
export const groupOverviewSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'group').map((entry) => entry.slug),
);

/** Slugs of canonical guide pages committed as docs/<slug>.md. */
export const canonicalPageSlugs = new Set(
  docsNav.filter((entry) => entry.kind === 'page').map((entry) => entry.slug),
);
